In [20]:
import numpy as np
%matplotlib inline

In [21]:
n = np.array([[1,2,3], [1,5,6]])
n

array([[1, 2, 3],
       [1, 5, 6]])

In [22]:
n[1,:]  # column by index

array([1, 5, 6])

In [23]:
n[0,:]  # row by index

array([1, 2, 3])

In [24]:
n[1,1] # item by row,column index

5

In [25]:
m = np.zeros((10,10))